### ISSUE TITLE
realpath command not found on Mac OSX

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/biop-bash-scripts#11]
Hi @hedjour!

I've finally tested the script on Mac OSX, and it seems that the command 'realpath' do not exist - thus the installer (full_install.sh) fails immediately... Do you know if there's a cross platform alternative ?

**Comment by hedjour** [comment]
I just see your message I 'm on it

**Comment by NicoKiaru** [comment]
No worry, I found a solution, sorry!

**Comment by hedjour** [comment]
Oh thanks.

**Comment by NicoKiaru** [comment]
OUps sorry, closed too eearly

> We can reduce the code by using [cond1] || [Cond2] cond 1 et cond2 are Linux and Windows which have the same commands.


Did you make a PR already ? I don't remember

**Comment by hedjour** [comment]
Yes I think
